imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "postgres://cicero:@127.0.0.1:5432/cicero?sslmode=disable"

[[env]]
name = "LOKI_ADDR"
value = "http://127.0.0.1:3100"

[[env]]
name = "ENCODE_LOGS_AS_JSON"
value = "false"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "golangci-lint"

[[commands]]
package = "gouml"

[[commands]]
package = "schemathesis"

[[commands]]
package = "nomad"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "golangci-lint run && gocritic check -enableAll -disable=ifElseChain,ptrToRefParam,unnamedResult,appendAssign ./... && nixpkgs-fmt --check ."
help = "Run code linters"

[[commands]]
package = "nomad-dev"
help = "Run Nomad in development mode with Nix driver"

[[commands]]
name = "psqlc"
command = "psql -d \"$DATABASE_URL\" \"$@\""
help = "psql into Cicero DB"

[[commands]]
name = "dev-run"
command = "cue export ./jobs -e jobs.dev | nomad run -"
help = "run postgres and loki in nomad"

[devshell]
name = "cicero"
packages = [
  "cicero-evaluator-nix",
  "cue",
  "diffutils",
  "gcc",
  "go",
  "gocode",
  "gocritic",
  "goimports",
  "gopls",
  "grafana-loki",
  "nixpkgs-fmt",
  "nomad-follower",
  "postgresql_12",
  "vector",
  "treefmt",
  "go-mockery",
  "httpie",
]
