imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "postgres://cicero:@127.0.0.1:5432/cicero?sslmode=disable"

[[env]]
name = "LOKI_ADDR"
value = "http://127.0.0.1:3100"

[[env]]
name = "CONSOLE_LOGGING_ENABLED"
value = "true"

[[env]]
name = "VAULT_ADDR"
value = "http://127.0.0.1:8200"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "gouml"

[[commands]]
package = "schemathesis"

[[commands]]
package = "nomad"

[[commands]]
package = "vault"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "golangci-lint run -E gocritic && treefmt --fail-on-change"
help = "Run code linters"

[[commands]]
package = "nix-cache"
help = "Run nix-cache-proxy, shares /nix/store between host & nomad tasks"

[[commands]]
package = "dev-cluster-full"
help = "Run nix-cache-proxy & dev-cluster"

[[commands]]
package = "dev-cluster"
help = "Run Nomad and Vault in development mode with Nix driver"

[[commands]]
name = "dev-jobs"
command = "cue export ./jobs -e jobs.dev | nomad run -"
help = "Run Postgres and Loki in Nomad"

[[commands]]
name = "dev-cicero"
command = "dbmate up; go run . start --debug --transform dev-cicero-transformer"
help = "Run Cicero from source"

[[commands]]
name = "dev-cicero-transformer"
command = '''
#! /bin/sh
jq '
	.job[]?.datacenters |= . + ["dc1"] |
	.job[]?.group[]?.restart.attempts = 0 |
	.job[]?.group[]?.task[]?.env |= . + {
		CICERO_WEB_URL: "http://127.0.0.1:8080",
		CICERO_API_URL: "http://127.0.0.1:8080/api",
		NIX_CONFIG: "substituters = http://127.0.0.1:7745/cache?compression=none\n\(.NIX_CONFIG)",
	} |
	.job[]?.group[]?.task[]?.vault.policies |= . + ["cicero"]
'
'''
help = "configures Nomad jobs for local dev environment"

[[commands]]
name = "psqlc"
command = "psql -d \"$DATABASE_URL\" \"$@\""
help = "psql into Cicero DB"

[devshell]
name = "cicero"
packages = [
  # cicero
  "cicero-evaluator-nix",

  # go
  "go",
  "gcc",
  "gocode",
  "goimports",
  "gopls",
  "go-mockery",
  "golangci-lint",

  # formatting
  "treefmt",
  "nixpkgs-fmt",

  # deployment
  "cue",
  "nomad-follower",
  "postgresql_12",
  "vector",
  "grafana-loki",

  # tools
  "httpie",
  "curlie",
  "diffutils",
  "jq",
]
