imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "postgres://cicero:@127.0.0.1:5432/cicero?sslmode=disable"

[[env]]
name = "LOKI_ADDR"
value = "http://127.0.0.1:3100"

[[env]]
name = "CONSOLE_LOGGING_ENABLED"
value = "true"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "gouml"

[[commands]]
package = "schemathesis"

[[commands]]
package = "nomad"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "golangci-lint run -E gocritic && treefmt --fail-on-change"
help = "Run code linters"

[[commands]]
package = "nomad-dev"
help = "Run Nomad in development mode with Nix driver"

[[commands]]
name = "dev-run"
command = "cue export ./jobs -e jobs.dev | nomad run -"
help = "run postgres and loki in nomad"

[[commands]]
name = "psqlc"
command = "psql -d \"$DATABASE_URL\" \"$@\""
help = "psql into Cicero DB"

[devshell]
name = "cicero"
packages = [
  # cicero
  "cicero-evaluator-nix",

  # go
  "go",
  "gcc",
  "gocode",
  "goimports",
  "gopls",
  "go-mockery",
  "golangci-lint",

  # formatting
  "treefmt",
  "nixpkgs-fmt",

  # deployment
  "cue",
  "nomad-follower",
  "postgresql_12",
  "vector",
  "grafana-loki",

  # tools
  "httpie",
  "diffutils",
]
