imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "sqlite:db/database.sqlite3"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "golangci-lint"

[[commands]]
package = "liftbridge-cli"

[[commands]]
package = "liftbridge"

[[commands]]
package = "foreman"

[[commands]]
package = "gouml"

[[commands]]
package = "nomad"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "gocritic check -enableAll ./... && fd -e nix -X nixfmt -c"
help = "Run code linters"

[devshell]
name = "cicero"
packages = [
  "diffutils",
  "go",
  "goimports",
  "gopls",
  "gocode",
  "gcc",
  "sqliteInteractive",
  "gocritic",
  "fd",
  "nixfmt",
]
