imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "postgres://postgres:@127.0.0.1:5432/cicero?sslmode=disable"

[[env]]
name = "LOKI_ADDR"
value = "http://127.0.0.1:3100"

[[env]]
name = "CONSOLE_LOGGING_ENABLED"
value = "true"

[[env]]
name = "VAULT_ADDR"
value = "http://127.0.0.1:8200"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "gouml"

[[commands]]
package = "schemathesis"

[[commands]]
package = "nomad"

[[commands]]
package = "vault"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "golangci-lint run -E gocritic --timeout 5m && treefmt --fail-on-change"
help = "Run code linters"

[[commands]]
name = "dev-cicero"
command = "dbmate up; go run . start --log-level trace --transform dev-cicero-transformer \"$@\""
help = "Run Cicero from source"

[[commands]]
name = "psqlc"
command = "psql -d \"$DATABASE_URL\" \"$@\""
help = "psql into Cicero DB"

[devshell]
name = "cicero"
packages = [
  # cicero
  "cicero-evaluator-nix",
  "dev-cicero-transformer",

  # go
  "go",
  "gcc",
  "gocode",
  "gotools",
  "gopls",
  "go-mockery",
  "golangci-lint",

  # formatting
  "treefmt",
  "alejandra",

  # deployment
  "cue",
  "nomad-follower",
  "postgresql",
  "vector",
  "grafana-loki",

  # tools
  "nixos-shell",
  "httpie",
  "curlie",
  "diffutils",
  "jq",
]
