[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.cue]
command = "cue"
options = ["fmt"]
includes = ["*.cue"]
